name = "VBlog"
license = "MIT"
licenselink = "https://github.com/EugeneVdovenko/VBlogHugoTheme/blob/master/LICENSE"
description = "Тема для блога на Hugo"
homepage = "https://vdovenko.net/"
tags = ["blog"]
features = ["Google Tag Manager"]
min_version = "0.73.0"

[author]
  name = "Eugene Vdovenko"
  homepage = "https://vdovenko.net"
