# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "VBlog"
license = "MIT"
licenselink = "https://github.com/eugenevdovenko/VBlog/blob/master/LICENSE"
description = ""
homepage = "https://vdovenko.net/"
tags = ["blog"]
features = ["Google Tag Manager"]
min_version = "0.73.0"

[author]
  name = "Eugene Vdovenko"
  homepage = "https://vdovenko.net"
